env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  CDN_DISTRIBUTION_ID: EJDECDYLB54TF
  CDN_BUCKET: s3://stackage.serokell.io

steps:
  - label: nix-build
    commands:
      - nix-build release.nix
  - wait
  - label: deploy
    branches: master
    commands:
      - nix-build release.nix
      - nix run nixpkgs.awscli -c
          aws s3 sync result/ "$CDN_BUCKET"
      - nix run nixpkgs.awscli -c
          aws cloudfront create-invalidation --distribution-id "$CDN_DISTRIBUTION_ID" --paths '/*'
